### ISSUE TITLE
Statistics to be seen in PRIDE Archive

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#1]
Hi @all: 

I would like to have your feedback about which statistics you would like to see from PRIDE Archive in plots. Something similar like www.omicsdi.org home page but we can look for new things. Please add here your feedback.

**Comment by ypriverol** [comment]
My first plot will be, a number of submissions per week/month/year with PARTIAL, COMPLETE, TOTAL. I suggest we can plot three lines one (TOTAL), second (PARTIAL), third (COMPLETE). The user should be able to switch between weekly, monthly and yearly. Something like:

**Comment by ypriverol** [comment]
The second plot I recommend and statistics is number of RAW files by instruments, but organize instruments hierarchical, something like https://bl.ocks.org/kerryrodden/7090426

<img width="961" alt="screen shot 2018-06-17 at 09 49 09" src="https://user-images.githubusercontent.com/52113/41506334-b91c1f00-7213-11e8-9e2e-8c25cdec3e30.png">

**Comment by J-Andy** [comment]
I agree - we should have a Data Growth Plot.
 
Here is how it looks like in JPost:
![image](https://user-images.githubusercontent.com/14042348/41507445-7a815f14-722a-11e8-9e47-b145c178f3da.png)

**Comment by J-Andy** [comment]
I would like to see a world map with number of submissions from each country as a landing page.
It is hard to pick the best library for this, but here are some examples:

![image](https://user-images.githubusercontent.com/14042348/41507466-cdffb438-722a-11e8-9297-70fee77f4044.png)

![image](https://user-images.githubusercontent.com/14042348/41507476-ee063cf2-722a-11e8-8339-6e7ca515a9e2.png)

![image](https://user-images.githubusercontent.com/14042348/41507480-02add944-722b-11e8-8cad-f761e381a4fd.png)

**Comment by sureshhewabi** [comment]
I think we can draw all of those plots d3.js (https://github.com/d3/d3/wiki/Gallery) it has a nice collection of plots with examples

**Comment by J-Andy** [comment]
There should be a plain box with general statistics about the resource (# of datasets, # of users, etc.) somewhere. I don't think we need to do fancy graphics for that, something like in OmicDI should be enough:

![image](https://user-images.githubusercontent.com/14042348/41507517-87377cce-722b-11e8-81ff-5f45253a6130.png)

**Comment by J-Andy** [comment]
We probably don't want to have too many visualizations on the main page - one or two is OK. Otherwise it becomes too 'crowded' in my opinion.

Yasset and Bai can have the final pick.

**Comment by ypriverol** [comment]
Yes, @sureshhewabi we have been using #D3 in omicsdi before. Thanks for the feedback. In the first iteration we will need to think only in plots that has levels complexity between 1/2 ;) . for example the map has more complexity, specially if we want to make then reponsive. The second problem that we have with that plot is that we don't have a way to trace the countries in PRIDE rigth now. I have implemented in mongo a way to trace that, but it will take some time to be annotated.

**Comment by ypriverol** [comment]
This has been done already.
