### ISSUE TITLE
The only entry point with search should be in projects

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#13]
The current implementation of the API has a search entry point for **files**

-  http://wwwdev.ebi.ac.uk/pride/ws/archive/search/files?pageSize=100

This should be merged with the files entry point: 

- http://wwwdev.ebi.ac.uk/pride/ws/archive/files?pageSize=100

**Comment by avinash-dev** [comment]
this has been resolved and pushed to wwwdev
