### ISSUE TITLE
Sort methods for the API are missing 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#19]
We need to implement the sort methods for the Web. Especially for search.

**Comment by ypriverol** [comment]
We should be able to sort the search results of Projects by the following properties: 

- **Relevance**: How close is my search queries to the result. 
- **Submission Date**: Submission Date. 
- **Project Identifier**: PRoject Identifier. 
- **

**Comment by avinash-dev** [comment]
Done and deployed.
Test cases and documentation updated accordingly.
