### ISSUE TITLE
Implements a documentation system for the API 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#4]
We need to implement a documentation system that allows developers to query our API. This is not only the SWAGGER documentation but also the query language for search, filter and facet projects including examples, etc. 

- [x] Implements Documentation system for the API. (Options: https://idratherbewriting.com/learnapidoc/pubapis_combine_swagger_and_guide.html)
    https://nordicapis.com/ultimate-guide-to-30-api-documentation-solutions/

- [x] Its needs to contain examples of how to query the API, the filtering language, etc.

**Comment by ypriverol** [comment]
https://github.com/TwineHealth/TwineDeveloperDocs

**Comment by avinash-dev** [comment]
@ypriverol  yes, on it!

**Comment by avinash-dev** [comment]
Done!
Commited to master and deployed to wwwdev
