### ISSUE TITLE
The following endpoint is failing 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#44]
If you go to the end point https://wwwdev.ebi.ac.uk/pride/ws/archive/peptideevidences?pageSize=100&sortDirection=DESC&sortConditions=projectAccession and click in the psms link for one of the peptides 

```
psms: {
href: "https://wwwdev.ebi.ac.uk/pride/ws/archive/peptideevidences/PXD013009:105934:M1DB88:QLFDSR/psms"
}
}
```
The application fails.

**Comment by proteomics-developers** [comment]
dependency issues
