### ISSUE TITLE
Modifications is not a faset

### ISSUE THREAD

**Issue by shabai517** [PRIDE-Archive/pride-archive-api#5]
check the api

http://ves-pg-41:9020/facet/projects?dateGap=%2B1YEAR&facetPageSize=100

**Comment by avinash-dev** [comment]
- **project_identified_ptms_facet** field is available in Solr Schema definitions

- Value not present in HH and HX solr instances

- On running Test for OracleSolrRepositoryTests.java::findAll(), the **project_identified_ptms_facet** field is being inserted into Local Solr successfully

- Probably need to run the pipeline for solr prod insertion and check.

**Comment by ypriverol** [comment]
I have implemented now and fix the pipeline to do the facet. @avinash-dev can you check that is working in the API. If that is the case, just let us know here.

**Comment by avinash-dev** [comment]
Just checked the API and it is returning facets for modifications with the field name project_identified_ptms_facet. @shabai517 can you please verify this from UI?
![sketch](https://user-images.githubusercontent.com/38186273/44335279-d82bb880-a46b-11e8-99b0-5d54cd1d4125.png)

**Comment by ypriverol** [comment]
ok I will test the frontend.

**Comment by ypriverol** [comment]
@avinash-dev can you check in the API why this query (URL) is failing http://ves-pg-41:9020/search/projects?keyword=&filter=project_identified_ptms_facet%3D%3DAcetylated+residue&page=0&pageSize=20&dateGap=%2B1YEAR

**Comment by avinash-dev** [comment]
This fix worked in local machine

**Comment by ypriverol** [comment]
I will deploy today after fix the prodcution error.

**Comment by shabai517** [comment]
PTMs works fine in the front end. I have pushed the code onto master.

**Comment by ypriverol** [comment]
The api already works. 

@shabai517 this is the structure of the query: 

http://ves-pg-41:9020/facet/projects?keyword=*%3A*&filter=project_identified_ptms_facet%3D%3DAcetylated%20residue&facetPageSize=100&dateGap=%2B1YEAR
