### ISSUE TITLE
Error in this call

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#58]
https://www.ebi.ac.uk/pride/ws/archive/v2/peptideevidences?proteinAccession=MOES_HUMAN&projectAccession=PXD015890&assayAccession=114346&sortConditions=projectAccession&sortDirection=DESC&page=0&pageSize=1000

**Comment by chakrabandla** [comment]
'psmAccessions' is null. please check the below object.

PrideMongoPeptideEvidence(id=5dc57dab9888895fd68ff7a2, peptideAccession=DVSEELIQ, proteinAccession=MOES_HUMAN, assayAccession=114346, projectAccession=PXD015890, peptideSequence=DVSEELIQ, database=null, ptmList=[], bestPSMScore=null, additionalAttributes=[CvParam{cvLabel='MS', accession='MS:1001868', name='distinct peptide-level q-value', value='0'}, CvParam{cvLabel='PRIDE', accession='PRIDE:0000511', name='Pass submitter threshold', value='true'}, CvParam{cvLabel='MS', accession='MS:1002360', name='distinct peptide-level FDRScore', value='0.00003'}], **_psmAccessions=null_**, isDecoy=false, startPosition=88, endPosition=95, missedCleavages=0, qualityEstimationMethods=[CvParam{cvLabel='MS', accession='MS:1001194', name='quality estimation with decoy database', value='false'}], isValid=false)

**Comment by chakrabandla** [comment]
@ypriverol @shabai517 fixed

**Comment by ypriverol** [comment]
Error fixed.
