### ISSUE TITLE
API parameter documentation for swagger

### ISSUE THREAD

**Issue by mwalzer** [PRIDE-Archive/pride-archive-api#61]
In swagger API parameters descriptions are just their name. Like below
![image](https://user-images.githubusercontent.com/5859205/70164298-d3b6fd80-16b8-11ea-85cd-233da59f171a.png)
I've seen more description on the parameters in the long-form documentation. Can we move/copy that to swagger?

**Comment by chakrabandla** [comment]
most of it is done.. only very few are remaining
